  minio:
    endpoint: http://localhost:9000
    access-key: admin
    secret-key: password123
    bucket: file

  file:
    client-path: /file
    storage-location: D:\\uploadFile\\
    base-uri: http://localhost:${server.port}${file.client-path}

  spring:
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            format_sql: true

    datasource:
      driver-class-name: org.postgresql.Driver
      url: ${url}
      username: ${username}
      password: ${password}
    application:
      name: DataJpa
  server:
    port: 8088